tokenizers:
  default:
    bewer.preprocessing.tokenization.strip_punctuation_keep_symbols_pattern:
      split_on_escaped: "-/'"
normalizers:
  default:
    bewer.preprocessing.normalization.lowercase:
    bewer.preprocessing.normalization.transliterate_latin_letters:
      preserve: "àâäçéèêëîïôöùûüÿœæ"
    bewer.preprocessing.normalization.transliterate_symbols:
